services:
  test:
    build: ./src
    command: alembic upgrade head && pytest -v
    volumes:
      - ./src:/src
    environment:
      - DATABASE_URL=postgresql://test:test@testdb:5432/test
    depends_on:
      - testdb

  testdb:
    image: postgres:14.5
    restart: always
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    ports:
      - "127.0.0.1:22432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
