"""create url table

Revision ID: 0a0189f2234e
Revises: 
Create Date: 2022-12-12 21:24:33.891948

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a0189f2234e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'url',
        sa.Column('id', sa.Integer(), unique=True),
        sa.Column('original_url', sa.Text, nullable=True),
        sa.Column('short_url', sa.Text, nullable=False, unique=True),
        sa.Column('clicks', sa.BigInteger, default=0),
        sa.Column('created_at', sa.DateTime),
        sa.Column('expires_at', sa.DateTime),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_short_url'), 'url', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_short_url'), table_name='url')
    op.drop_table('url')
    # ### end Alembic commands ###
